//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFM.Submissions.GovGateway.EdrsPollRequestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://poll.drsv1_0.ws.bg.lr.gov/", ConfigurationName="EdrsPollRequestService.EDocumentRegistrationV1_0PollRequestService")]
    public interface EDocumentRegistrationV1_0PollRequestService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="SOAPEngineSystemException")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="SchemaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseResponse getResponse(LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseResponse> getResponseAsync(LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg/MR01-20090605/PollRequest")]
    public partial class PollRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Q1IdentifierType idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Q1IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg/MR01-20090605/PollRequest")]
    public partial class Q1IdentifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageIDTextType messageIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageIDTextType MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg/MR01-20090605/PollRequest")]
    public partial class MessageIDTextType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class ScheduleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string scheduleType1Field;
        
        private RegisterEntryType[] scheduleEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScheduleType", Order=0)]
        public string ScheduleType1 {
            get {
                return this.scheduleType1Field;
            }
            set {
                this.scheduleType1Field = value;
                this.RaisePropertyChanged("ScheduleType1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScheduleEntry", Order=1)]
        public RegisterEntryType[] ScheduleEntry {
            get {
                return this.scheduleEntryField;
            }
            set {
                this.scheduleEntryField = value;
                this.RaisePropertyChanged("ScheduleEntry");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class RegisterEntryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entryNumberField;
        
        private string entryDateField;
        
        private string entryTypeField;
        
        private string[] entryTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntryNumber {
            get {
                return this.entryNumberField;
            }
            set {
                this.entryNumberField = value;
                this.RaisePropertyChanged("EntryNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntryDate {
            get {
                return this.entryDateField;
            }
            set {
                this.entryDateField = value;
                this.RaisePropertyChanged("EntryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EntryType {
            get {
                return this.entryTypeField;
            }
            set {
                this.entryTypeField = value;
                this.RaisePropertyChanged("EntryType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EntryText", Order=3)]
        public string[] EntryText {
            get {
                return this.entryTextField;
            }
            set {
                this.entryTextField = value;
                this.RaisePropertyChanged("EntryText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class RegisterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] districtDetailsField;
        
        private RegisterEntryType[] registerEntryField;
        
        private ScheduleType[] scheduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EntryText", IsNullable=false)]
        public string[] DistrictDetails {
            get {
                return this.districtDetailsField;
            }
            set {
                this.districtDetailsField = value;
                this.RaisePropertyChanged("DistrictDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegisterEntry", Order=1)]
        public RegisterEntryType[] RegisterEntry {
            get {
                return this.registerEntryField;
            }
            set {
                this.registerEntryField = value;
                this.RaisePropertyChanged("RegisterEntry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Schedule", Order=2)]
        public ScheduleType[] Schedule {
            get {
                return this.scheduleField;
            }
            set {
                this.scheduleField = value;
                this.RaisePropertyChanged("Schedule");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class XmlRegisterDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleNumberField;
        
        private RegisterType propertyRegisterField;
        
        private RegisterType proprietorshipRegisterField;
        
        private RegisterType chargesRegisterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TitleNumber {
            get {
                return this.titleNumberField;
            }
            set {
                this.titleNumberField = value;
                this.RaisePropertyChanged("TitleNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RegisterType PropertyRegister {
            get {
                return this.propertyRegisterField;
            }
            set {
                this.propertyRegisterField = value;
                this.RaisePropertyChanged("PropertyRegister");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RegisterType ProprietorshipRegister {
            get {
                return this.proprietorshipRegisterField;
            }
            set {
                this.proprietorshipRegisterField = value;
                this.RaisePropertyChanged("ProprietorshipRegister");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public RegisterType ChargesRegister {
            get {
                return this.chargesRegisterField;
            }
            set {
                this.chargesRegisterField = value;
                this.RaisePropertyChanged("ChargesRegister");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class XmlRegistersType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private XmlRegisterDataType[] xmlRegisterDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XmlRegisterData", Order=0)]
        public XmlRegisterDataType[] XmlRegisterData {
            get {
                return this.xmlRegisterDataField;
            }
            set {
                this.xmlRegisterDataField = value;
                this.RaisePropertyChanged("XmlRegisterData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class AttachmentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string filenameField;
        
        private string formatField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class ResultsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageDetailsField;
        
        private string externalReferenceField;
        
        private int actualFeeField;
        
        private bool earlyCompletionIndicatorField;
        
        private bool earlyCompletionIndicatorFieldSpecified;
        
        private bool additionalDespatchItemsIndicatorField;
        
        private bool additionalDespatchItemsIndicatorFieldSpecified;
        
        private ResultCodeContentType resultTypeCodeField;
        
        private AttachmentType despatchDocumentField;
        
        private XmlRegistersType xmlRegistersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageDetails {
            get {
                return this.messageDetailsField;
            }
            set {
                this.messageDetailsField = value;
                this.RaisePropertyChanged("MessageDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
                this.RaisePropertyChanged("ExternalReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ActualFee {
            get {
                return this.actualFeeField;
            }
            set {
                this.actualFeeField = value;
                this.RaisePropertyChanged("ActualFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool EarlyCompletionIndicator {
            get {
                return this.earlyCompletionIndicatorField;
            }
            set {
                this.earlyCompletionIndicatorField = value;
                this.RaisePropertyChanged("EarlyCompletionIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EarlyCompletionIndicatorSpecified {
            get {
                return this.earlyCompletionIndicatorFieldSpecified;
            }
            set {
                this.earlyCompletionIndicatorFieldSpecified = value;
                this.RaisePropertyChanged("EarlyCompletionIndicatorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool AdditionalDespatchItemsIndicator {
            get {
                return this.additionalDespatchItemsIndicatorField;
            }
            set {
                this.additionalDespatchItemsIndicatorField = value;
                this.RaisePropertyChanged("AdditionalDespatchItemsIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdditionalDespatchItemsIndicatorSpecified {
            get {
                return this.additionalDespatchItemsIndicatorFieldSpecified;
            }
            set {
                this.additionalDespatchItemsIndicatorFieldSpecified = value;
                this.RaisePropertyChanged("AdditionalDespatchItemsIndicatorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ResultCodeContentType ResultTypeCode {
            get {
                return this.resultTypeCodeField;
            }
            set {
                this.resultTypeCodeField = value;
                this.RaisePropertyChanged("ResultTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public AttachmentType DespatchDocument {
            get {
                return this.despatchDocumentField;
            }
            set {
                this.despatchDocumentField = value;
                this.RaisePropertyChanged("DespatchDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public XmlRegistersType XmlRegisters {
            get {
                return this.xmlRegistersField;
            }
            set {
                this.xmlRegistersField = value;
                this.RaisePropertyChanged("XmlRegisters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public enum ResultCodeContentType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class ValidationErrorsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class RejectionResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string reasonField;
        
        private string codeField;
        
        private string otherDescriptionField;
        
        private ValidationErrorsType[] validationErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OtherDescription {
            get {
                return this.otherDescriptionField;
            }
            set {
                this.otherDescriptionField = value;
                this.RaisePropertyChanged("OtherDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValidationErrors", Order=3)]
        public ValidationErrorsType[] ValidationErrors {
            get {
                return this.validationErrorsField;
            }
            set {
                this.validationErrorsField = value;
                this.RaisePropertyChanged("ValidationErrors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class RejectionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string externalReferenceField;
        
        private RejectionResponseType rejectionResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
                this.RaisePropertyChanged("ExternalReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RejectionResponseType RejectionResponse {
            get {
                return this.rejectionResponseField;
            }
            set {
                this.rejectionResponseField = value;
                this.RaisePropertyChanged("RejectionResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class AcknowledgementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uniqueIDField;
        
        private string messageDescriptionField;
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
                this.RaisePropertyChanged("UniqueID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageDescription {
            get {
                return this.messageDescriptionField;
            }
            set {
                this.messageDescriptionField = value;
                this.RaisePropertyChanged("MessageDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ABR", typeof(string), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("ExpectedResponseDateTime", typeof(System.DateTime), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("PriorityDateTime", typeof(System.DateTime), Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        ABR,
        
        /// <remarks/>
        ExpectedResponseDateTime,
        
        /// <remarks/>
        PriorityDateTime,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class GatewayResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProductResponseCodeContentType typeCodeField;
        
        private AcknowledgementType acknowledgementField;
        
        private RejectionType rejectionField;
        
        private ResultsType resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProductResponseCodeContentType TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AcknowledgementType Acknowledgement {
            get {
                return this.acknowledgementField;
            }
            set {
                this.acknowledgementField = value;
                this.RaisePropertyChanged("Acknowledgement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RejectionType Rejection {
            get {
                return this.rejectionField;
            }
            set {
                this.rejectionField = value;
                this.RaisePropertyChanged("Rejection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ResultsType Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public enum ProductResponseCodeContentType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseApplicationToChangeRegisterV1_0")]
    public partial class ResponseApplicationToChangeRegisterV1_0Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GatewayResponseType gatewayResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GatewayResponseType GatewayResponse {
            get {
                return this.gatewayResponseField;
            }
            set {
                this.gatewayResponseField = value;
                this.RaisePropertyChanged("GatewayResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResponse", WrapperNamespace="http://poll.drsv1_0.ws.bg.lr.gov/", IsWrapped=true)]
    public partial class getResponseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://poll.drsv1_0.ws.bg.lr.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LFM.Submissions.GovGateway.EdrsPollRequestService.PollRequestType arg0;
        
        public getResponseRequest() {
        }
        
        public getResponseRequest(LFM.Submissions.GovGateway.EdrsPollRequestService.PollRequestType arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResponseResponse", WrapperNamespace="http://poll.drsv1_0.ws.bg.lr.gov/", IsWrapped=true)]
    public partial class getResponseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://poll.drsv1_0.ws.bg.lr.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LFM.Submissions.GovGateway.EdrsPollRequestService.ResponseApplicationToChangeRegisterV1_0Type @return;
        
        public getResponseResponse() {
        }
        
        public getResponseResponse(LFM.Submissions.GovGateway.EdrsPollRequestService.ResponseApplicationToChangeRegisterV1_0Type @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EDocumentRegistrationV1_0PollRequestServiceChannel : LFM.Submissions.GovGateway.EdrsPollRequestService.EDocumentRegistrationV1_0PollRequestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDocumentRegistrationV1_0PollRequestServiceClient : System.ServiceModel.ClientBase<LFM.Submissions.GovGateway.EdrsPollRequestService.EDocumentRegistrationV1_0PollRequestService>, LFM.Submissions.GovGateway.EdrsPollRequestService.EDocumentRegistrationV1_0PollRequestService {
        
        public EDocumentRegistrationV1_0PollRequestServiceClient() {
        }
        
        public EDocumentRegistrationV1_0PollRequestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDocumentRegistrationV1_0PollRequestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDocumentRegistrationV1_0PollRequestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDocumentRegistrationV1_0PollRequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseResponse LFM.Submissions.GovGateway.EdrsPollRequestService.EDocumentRegistrationV1_0PollRequestService.getResponse(LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseRequest request) {
            return base.Channel.getResponse(request);
        }
        
        public LFM.Submissions.GovGateway.EdrsPollRequestService.ResponseApplicationToChangeRegisterV1_0Type getResponse(LFM.Submissions.GovGateway.EdrsPollRequestService.PollRequestType arg0) {
            LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseRequest inValue = new LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseRequest();
            inValue.arg0 = arg0;
            LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseResponse retVal = ((LFM.Submissions.GovGateway.EdrsPollRequestService.EDocumentRegistrationV1_0PollRequestService)(this)).getResponse(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseResponse> LFM.Submissions.GovGateway.EdrsPollRequestService.EDocumentRegistrationV1_0PollRequestService.getResponseAsync(LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseRequest request) {
            return base.Channel.getResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseResponse> getResponseAsync(LFM.Submissions.GovGateway.EdrsPollRequestService.PollRequestType arg0) {
            LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseRequest inValue = new LFM.Submissions.GovGateway.EdrsPollRequestService.getResponseRequest();
            inValue.arg0 = arg0;
            return ((LFM.Submissions.GovGateway.EdrsPollRequestService.EDocumentRegistrationV1_0PollRequestService)(this)).getResponseAsync(inValue);
        }
    }
}
