//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFM.Submissions.AgentServices.EarlyCompletionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://poll.earlycompletionv1_0.ws.bg.lr.gov/", ConfigurationName="EarlyCompletionService.EarlyCompletionV1_0PollRequestService")]
    public interface EarlyCompletionV1_0PollRequestService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="SOAPEngineSystemException")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="SchemaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LFM.Submissions.AgentServices.EarlyCompletionService.getResponseResponse getResponse(LFM.Submissions.AgentServices.EarlyCompletionService.getResponseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LFM.Submissions.AgentServices.EarlyCompletionService.getResponseResponse> getResponseAsync(LFM.Submissions.AgentServices.EarlyCompletionService.getResponseRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg/MR01-20090605/PollRequest")]
    public partial class PollRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Q1IdentifierType idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Q1IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg/MR01-20090605/PollRequest")]
    public partial class Q1IdentifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageIDTextType messageIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageIDTextType MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg/MR01-20090605/PollRequest")]
    public partial class MessageIDTextType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseEarlyCompletionV1_0")]
    public partial class ScheduleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string scheduleType1Field;
        
        private RegisterEntryType[] scheduleEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScheduleType", Order=0)]
        public string ScheduleType1 {
            get {
                return this.scheduleType1Field;
            }
            set {
                this.scheduleType1Field = value;
                this.RaisePropertyChanged("ScheduleType1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScheduleEntry", Order=1)]
        public RegisterEntryType[] ScheduleEntry {
            get {
                return this.scheduleEntryField;
            }
            set {
                this.scheduleEntryField = value;
                this.RaisePropertyChanged("ScheduleEntry");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseEarlyCompletionV1_0")]
    public partial class RegisterEntryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entryNumberField;
        
        private string entryDateField;
        
        private string entryTypeField;
        
        private string[] entryTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntryNumber {
            get {
                return this.entryNumberField;
            }
            set {
                this.entryNumberField = value;
                this.RaisePropertyChanged("EntryNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntryDate {
            get {
                return this.entryDateField;
            }
            set {
                this.entryDateField = value;
                this.RaisePropertyChanged("EntryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EntryType {
            get {
                return this.entryTypeField;
            }
            set {
                this.entryTypeField = value;
                this.RaisePropertyChanged("EntryType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EntryText", Order=3)]
        public string[] EntryText {
            get {
                return this.entryTextField;
            }
            set {
                this.entryTextField = value;
                this.RaisePropertyChanged("EntryText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseEarlyCompletionV1_0")]
    public partial class RegisterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] districtDetailsField;
        
        private RegisterEntryType[] registerEntryField;
        
        private ScheduleType[] scheduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EntryText", IsNullable=false)]
        public string[] DistrictDetails {
            get {
                return this.districtDetailsField;
            }
            set {
                this.districtDetailsField = value;
                this.RaisePropertyChanged("DistrictDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegisterEntry", Order=1)]
        public RegisterEntryType[] RegisterEntry {
            get {
                return this.registerEntryField;
            }
            set {
                this.registerEntryField = value;
                this.RaisePropertyChanged("RegisterEntry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Schedule", Order=2)]
        public ScheduleType[] Schedule {
            get {
                return this.scheduleField;
            }
            set {
                this.scheduleField = value;
                this.RaisePropertyChanged("Schedule");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseEarlyCompletionV1_0")]
    public partial class XmlRegisterDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleNumberField;
        
        private RegisterType propertyRegisterField;
        
        private RegisterType proprietorshipRegisterField;
        
        private RegisterType chargesRegisterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TitleNumber {
            get {
                return this.titleNumberField;
            }
            set {
                this.titleNumberField = value;
                this.RaisePropertyChanged("TitleNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RegisterType PropertyRegister {
            get {
                return this.propertyRegisterField;
            }
            set {
                this.propertyRegisterField = value;
                this.RaisePropertyChanged("PropertyRegister");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RegisterType ProprietorshipRegister {
            get {
                return this.proprietorshipRegisterField;
            }
            set {
                this.proprietorshipRegisterField = value;
                this.RaisePropertyChanged("ProprietorshipRegister");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public RegisterType ChargesRegister {
            get {
                return this.chargesRegisterField;
            }
            set {
                this.chargesRegisterField = value;
                this.RaisePropertyChanged("ChargesRegister");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseEarlyCompletionV1_0")]
    public partial class AttachmentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string filenameField;
        
        private string formatField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseEarlyCompletionV1_0")]
    public partial class EarlyCompletionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationMessageIdField;
        
        private string externalReferenceField;
        
        private string aBRField;
        
        private AttachmentType despatchDocumentField;
        
        private XmlRegisterDataType xmlRegisterDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ApplicationMessageId {
            get {
                return this.applicationMessageIdField;
            }
            set {
                this.applicationMessageIdField = value;
                this.RaisePropertyChanged("ApplicationMessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
                this.RaisePropertyChanged("ExternalReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ABR {
            get {
                return this.aBRField;
            }
            set {
                this.aBRField = value;
                this.RaisePropertyChanged("ABR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AttachmentType DespatchDocument {
            get {
                return this.despatchDocumentField;
            }
            set {
                this.despatchDocumentField = value;
                this.RaisePropertyChanged("DespatchDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public XmlRegisterDataType XmlRegisterData {
            get {
                return this.xmlRegisterDataField;
            }
            set {
                this.xmlRegisterDataField = value;
                this.RaisePropertyChanged("XmlRegisterData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseEarlyCompletionV1_0")]
    public partial class GatewayResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProductResponseCodeContentType typeCodeField;
        
        private EarlyCompletionType earlyCompletionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProductResponseCodeContentType TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EarlyCompletionType EarlyCompletion {
            get {
                return this.earlyCompletionField;
            }
            set {
                this.earlyCompletionField = value;
                this.RaisePropertyChanged("EarlyCompletion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseEarlyCompletionV1_0")]
    public enum ProductResponseCodeContentType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2012/ResponseEarlyCompletionV1_0")]
    public partial class ResponseEarlyCompletionV1_0Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GatewayResponseType gatewayResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GatewayResponseType GatewayResponse {
            get {
                return this.gatewayResponseField;
            }
            set {
                this.gatewayResponseField = value;
                this.RaisePropertyChanged("GatewayResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResponse", WrapperNamespace="http://poll.earlycompletionv1_0.ws.bg.lr.gov/", IsWrapped=true)]
    public partial class getResponseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://poll.earlycompletionv1_0.ws.bg.lr.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LFM.Submissions.AgentServices.EarlyCompletionService.PollRequestType arg0;
        
        public getResponseRequest() {
        }
        
        public getResponseRequest(LFM.Submissions.AgentServices.EarlyCompletionService.PollRequestType arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResponseResponse", WrapperNamespace="http://poll.earlycompletionv1_0.ws.bg.lr.gov/", IsWrapped=true)]
    public partial class getResponseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://poll.earlycompletionv1_0.ws.bg.lr.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LFM.Submissions.AgentServices.EarlyCompletionService.ResponseEarlyCompletionV1_0Type @return;
        
        public getResponseResponse() {
        }
        
        public getResponseResponse(LFM.Submissions.AgentServices.EarlyCompletionService.ResponseEarlyCompletionV1_0Type @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EarlyCompletionV1_0PollRequestServiceChannel : LFM.Submissions.AgentServices.EarlyCompletionService.EarlyCompletionV1_0PollRequestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EarlyCompletionV1_0PollRequestServiceClient : System.ServiceModel.ClientBase<LFM.Submissions.AgentServices.EarlyCompletionService.EarlyCompletionV1_0PollRequestService>, LFM.Submissions.AgentServices.EarlyCompletionService.EarlyCompletionV1_0PollRequestService {
        
        public EarlyCompletionV1_0PollRequestServiceClient() {
        }
        
        public EarlyCompletionV1_0PollRequestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EarlyCompletionV1_0PollRequestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EarlyCompletionV1_0PollRequestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EarlyCompletionV1_0PollRequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LFM.Submissions.AgentServices.EarlyCompletionService.getResponseResponse LFM.Submissions.AgentServices.EarlyCompletionService.EarlyCompletionV1_0PollRequestService.getResponse(LFM.Submissions.AgentServices.EarlyCompletionService.getResponseRequest request) {
            return base.Channel.getResponse(request);
        }
        
        public LFM.Submissions.AgentServices.EarlyCompletionService.ResponseEarlyCompletionV1_0Type getResponse(LFM.Submissions.AgentServices.EarlyCompletionService.PollRequestType arg0) {
            LFM.Submissions.AgentServices.EarlyCompletionService.getResponseRequest inValue = new LFM.Submissions.AgentServices.EarlyCompletionService.getResponseRequest();
            inValue.arg0 = arg0;
            LFM.Submissions.AgentServices.EarlyCompletionService.getResponseResponse retVal = ((LFM.Submissions.AgentServices.EarlyCompletionService.EarlyCompletionV1_0PollRequestService)(this)).getResponse(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LFM.Submissions.AgentServices.EarlyCompletionService.getResponseResponse> LFM.Submissions.AgentServices.EarlyCompletionService.EarlyCompletionV1_0PollRequestService.getResponseAsync(LFM.Submissions.AgentServices.EarlyCompletionService.getResponseRequest request) {
            return base.Channel.getResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<LFM.Submissions.AgentServices.EarlyCompletionService.getResponseResponse> getResponseAsync(LFM.Submissions.AgentServices.EarlyCompletionService.PollRequestType arg0) {
            LFM.Submissions.AgentServices.EarlyCompletionService.getResponseRequest inValue = new LFM.Submissions.AgentServices.EarlyCompletionService.getResponseRequest();
            inValue.arg0 = arg0;
            return ((LFM.Submissions.AgentServices.EarlyCompletionService.EarlyCompletionV1_0PollRequestService)(this)).getResponseAsync(inValue);
        }
    }
}
