//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFM.Submissions.AgentServices.OutstandingRequestsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://outstandingrequestsv2_0.ws.bg.lr.gov/", ConfigurationName="OutstandingRequestsService.OutstandingRequestsV2_0Service")]
    public interface OutstandingRequestsV2_0Service {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="SOAPEngineSystemException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsResponse getOutstandingRequests(LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsResponse> getOutstandingRequestsAsync(LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/RequestOutstandingRequestsV2_0")]
    public partial class RequestOutstandingRequestsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Q1IdentifierType idField;
        
        private Q1OutstandingRequestsProductType productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Q1IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Q1OutstandingRequestsProductType Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("Product");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/RequestOutstandingRequestsV2_0")]
    public partial class Q1IdentifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Q1TextType messageIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Q1TextType MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/RequestOutstandingRequestsV2_0")]
    public partial class Q1TextType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseOutstandingRequestsV2_0")]
    public partial class NonEmptyTextType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseOutstandingRequestsV2_0")]
    public partial class Q1RejectionResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NonEmptyTextType reasonField;
        
        private NonEmptyTextType codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NonEmptyTextType Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NonEmptyTextType Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseOutstandingRequestsV2_0")]
    public partial class Q1RejectionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Q1RejectionResponseType rejectionResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Q1RejectionResponseType RejectionResponse {
            get {
                return this.rejectionResponseField;
            }
            set {
                this.rejectionResponseField = value;
                this.RaisePropertyChanged("RejectionResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseOutstandingRequestsV2_0")]
    public partial class DateTimeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="IndicatorType", Namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseOutstandingRequestsV2_0")]
    public partial class IndicatorType1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Q1IdentifierType", Namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseOutstandingRequestsV2_0")]
    public partial class Q1IdentifierType1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseOutstandingRequestsV2_0")]
    public partial class OutstandingRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Q1IdentifierType1 idField;
        
        private IndicatorType1 newResponseField;
        
        private int serviceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Q1IdentifierType1 ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IndicatorType1 NewResponse {
            get {
                return this.newResponseField;
            }
            set {
                this.newResponseField = value;
                this.RaisePropertyChanged("NewResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("ServiceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseOutstandingRequestsV2_0")]
    public partial class ResultsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OutstandingRequestType[] outstandingRequestsField;
        
        private DateTimeType resultDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OutstandingRequests", Order=0)]
        public OutstandingRequestType[] OutstandingRequests {
            get {
                return this.outstandingRequestsField;
            }
            set {
                this.outstandingRequestsField = value;
                this.RaisePropertyChanged("OutstandingRequests");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DateTimeType ResultDateTime {
            get {
                return this.resultDateTimeField;
            }
            set {
                this.resultDateTimeField = value;
                this.RaisePropertyChanged("ResultDateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseOutstandingRequestsV2_0")]
    public partial class ProductResponseCodeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProductResponseCodeContentType valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public ProductResponseCodeContentType Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseOutstandingRequestsV2_0")]
    public enum ProductResponseCodeContentType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseOutstandingRequestsV2_0")]
    public partial class ResponseOutstandingRequestsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProductResponseCodeType typeCodeField;
        
        private ResultsType resultsField;
        
        private Q1RejectionType rejectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProductResponseCodeType TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResultsType Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Q1RejectionType Rejection {
            get {
                return this.rejectionField;
            }
            set {
                this.rejectionField = value;
                this.RaisePropertyChanged("Rejection");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/RequestOutstandingRequestsV2_0")]
    public partial class IndicatorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oscre.org/ns/eReg-Final/2011/RequestOutstandingRequestsV2_0")]
    public partial class Q1OutstandingRequestsProductType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IndicatorType showOnlyNewResponsesField;
        
        private int specificServiceField;
        
        private bool specificServiceFieldSpecified;
        
        /// <remarks/>
        // CODEGEN Warning: 'default' attribute supported only for primitive types.  Ignoring default='false' attribute.
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndicatorType ShowOnlyNewResponses {
            get {
                return this.showOnlyNewResponsesField;
            }
            set {
                this.showOnlyNewResponsesField = value;
                this.RaisePropertyChanged("ShowOnlyNewResponses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SpecificService {
            get {
                return this.specificServiceField;
            }
            set {
                this.specificServiceField = value;
                this.RaisePropertyChanged("SpecificService");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpecificServiceSpecified {
            get {
                return this.specificServiceFieldSpecified;
            }
            set {
                this.specificServiceFieldSpecified = value;
                this.RaisePropertyChanged("SpecificServiceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOutstandingRequests", WrapperNamespace="http://outstandingrequestsv2_0.ws.bg.lr.gov/", IsWrapped=true)]
    public partial class getOutstandingRequestsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://outstandingrequestsv2_0.ws.bg.lr.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LFM.Submissions.AgentServices.OutstandingRequestsService.RequestOutstandingRequestsType arg0;
        
        public getOutstandingRequestsRequest() {
        }
        
        public getOutstandingRequestsRequest(LFM.Submissions.AgentServices.OutstandingRequestsService.RequestOutstandingRequestsType arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOutstandingRequestsResponse", WrapperNamespace="http://outstandingrequestsv2_0.ws.bg.lr.gov/", IsWrapped=true)]
    public partial class getOutstandingRequestsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://outstandingrequestsv2_0.ws.bg.lr.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LFM.Submissions.AgentServices.OutstandingRequestsService.ResponseOutstandingRequestsType @return;
        
        public getOutstandingRequestsResponse() {
        }
        
        public getOutstandingRequestsResponse(LFM.Submissions.AgentServices.OutstandingRequestsService.ResponseOutstandingRequestsType @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OutstandingRequestsV2_0ServiceChannel : LFM.Submissions.AgentServices.OutstandingRequestsService.OutstandingRequestsV2_0Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OutstandingRequestsV2_0ServiceClient : System.ServiceModel.ClientBase<LFM.Submissions.AgentServices.OutstandingRequestsService.OutstandingRequestsV2_0Service>, LFM.Submissions.AgentServices.OutstandingRequestsService.OutstandingRequestsV2_0Service {
        
        public OutstandingRequestsV2_0ServiceClient() {
        }
        
        public OutstandingRequestsV2_0ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OutstandingRequestsV2_0ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutstandingRequestsV2_0ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutstandingRequestsV2_0ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsResponse LFM.Submissions.AgentServices.OutstandingRequestsService.OutstandingRequestsV2_0Service.getOutstandingRequests(LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsRequest request) {
            return base.Channel.getOutstandingRequests(request);
        }
        
        public LFM.Submissions.AgentServices.OutstandingRequestsService.ResponseOutstandingRequestsType getOutstandingRequests(LFM.Submissions.AgentServices.OutstandingRequestsService.RequestOutstandingRequestsType arg0) {
            LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsRequest inValue = new LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsRequest();
            inValue.arg0 = arg0;
            LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsResponse retVal = ((LFM.Submissions.AgentServices.OutstandingRequestsService.OutstandingRequestsV2_0Service)(this)).getOutstandingRequests(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsResponse> LFM.Submissions.AgentServices.OutstandingRequestsService.OutstandingRequestsV2_0Service.getOutstandingRequestsAsync(LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsRequest request) {
            return base.Channel.getOutstandingRequestsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsResponse> getOutstandingRequestsAsync(LFM.Submissions.AgentServices.OutstandingRequestsService.RequestOutstandingRequestsType arg0) {
            LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsRequest inValue = new LFM.Submissions.AgentServices.OutstandingRequestsService.getOutstandingRequestsRequest();
            inValue.arg0 = arg0;
            return ((LFM.Submissions.AgentServices.OutstandingRequestsService.OutstandingRequestsV2_0Service)(this)).getOutstandingRequestsAsync(inValue);
        }
    }
}
